services:
  redis:
    image: redis:7-alpine
    container_name: video-streaming-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:latest 
    container_name: video-streaming-minio
    ports:
      - "9000:9000"   # api s3
      - "9001:9001"   # web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    restart: unless-stopped

volumes:
  redis-data: